### ISSUE TITLE
Why does 0.1+0.2 not equal 0.3, but 0.1+0.3 equals 0.4? And why we need the M to declare a decimal literal value? 

### ISSUE THREAD

**Issue by Nemonek** [markjprice/cs10dotnet6#120]
I was looking in the book to fix some imprecisions in my notes, and I noticed that when you do 0.1+0.2 == 0.3 , like you said in the book, it's false, but why 0.1 + 0.3 == 0.4 is true?
Then, I'm not sure I understood why we need to put an M in this:
```C#
decimal x = 0.1M;
```

**Comment by markjprice** [comment]
`0.1 + 0.3 == 0.4` is `true` because with `double` values, some values can be exactly represented but some numbers cannot. So some numbers can be directly compared but some cannot. I deliberately picked `0.1` and `0.2` to compare to `0.3` because they cannot be compared, as proven by the result.

If you say `decimal x = 0.1;` then the `0.1` is a `double`. A `double` cannot be implicitly converted to a `decimal` because it is potentially imprecise. You have to explicitly cast it to tell the compiler that you accept the potential consequences, or use `M` to indicate that you want to define a `decimal` literal value instead of a `double` literal value..

**Comment by Nemonek** [comment]
Thank you!
