### ISSUE TITLE
 class library creation

### ISSUE THREAD

**Issue by ghlouwho** [markjprice/cs10dotnet6#23]
P 162 #1.  Needs better explanation, this failed "dotnet new classlib CalculatorLib", Found this... https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio-code?pivots=dotnet-6-0, and then changed to "dotnet new classlib -o CalculatorLib"

**Comment by ghlouwho** [comment]
It  is also confusing as to what folder we should be working in.  Are we creating the class library in the Instrumenting folder, or a new CalculatorLib folder.  This is not written for people new to this.

**Comment by markjprice** [comment]
I instruct readers to follow the detailed steps in Chapter 1 whenver they create a new project. They are the same steps regardless of if you are creating a console app or class library (except the name of the template to use of course). 

1. Create a folder for the project named `CalculatorLib`.
2. Change to that folder.
3. Create the project using `dotnet new [templatename]` i.e. `dotnet new classlib`. 

But I agree it'd be worth repeating the detailed steps for this exercise since the change from `console` to `classlib` could make a reader not realize it is the same process as creating a console app. I also plan to explain the use of `-o` flag in Chapter 1 for readers who might prefer that way of creating a project.
