### ISSUE TITLE
More info should be included on 'add reference'

### ISSUE THREAD

**Issue by ghlouwho** [markjprice/cs10dotnet6#26]
P 163 #7.  Needs better explanation, this failed "dotnet add reference", got error "Required argument missing for command: reference".
Found this page, which gives more info, https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add-reference, but decided to "modify the configuration".

**Comment by ghlouwho** [comment]
P164.  #4 -  Not the first time that I have seen this in your book.  My .cs file has "namespace CalculatorLibUnitTests;", Your example says to eliminate the ';', and put in the brackets '[]'.  Is this something related to VS Code?

**Comment by markjprice** [comment]
The `dotnet add package` and `dotnet add reference` commands were explained previously on page 157. Obviously, if you need to add a package or reference you must specify what package or reference you want--it cannot guess for you. Or, just modify the `.csproj` file directly as shown on page 163. This is easiest since you can just copy and paste from the ebook or from the code solution.

**Comment by markjprice** [comment]
C# 10 and .NET 6 introduces a feature called **file-scoped namespace declarations**. I introduce it on page 180. It simplifies code by removing the need for curly braces { } to declare the types inside a namespace. Either the old or new syntax works correctly.

**Comment by markjprice** [comment]
Thank you for raising this issue. In the 7th edition I will add examples of using the `dotnet add` commands in Chapter 1 so readers know how to use them earlier. And all the code examples will be updated to use the file-scoped namespace declaration style too.

**Comment by ghlouwho** [comment]
P214 - #1 - You did not indicate if this is a new console, or classlib.

**Comment by ghlouwho** [comment]
Oh, just another .cs file, as part of the existing project.
