### ISSUE TITLE
Unable to documenting functions with XML comments

### ISSUE THREAD

**Issue by CoRB-ops** [markjprice/cs10dotnet6#3]
Hello,
Page 140-141. Took me some time to realise that for using the XML comments ( tooltip
with only basic information was popping out), functions should be outside the Main method. It would be nice to have some note about it in the errata. 

![net6 before](https://user-images.githubusercontent.com/73778850/142777778-8bfb6c4d-f6db-4aea-a275-0aa6b93a252d.png)

![net6 after](https://user-images.githubusercontent.com/73778850/142777780-e62c6d2b-d073-40ff-b89b-3c2789aaa537.png)

**Comment by markjprice** [comment]
This seems to be caused by a bug introduced in an update to the C# extension or Visual Studio Code or even .NET 6.0 since that code was tested a few months ago. I suspect it is to do with the functions being local to the hidden Program class that is generated implicitly. You do not need a Main method. Just wrapping all the code in any public class fixes the tooltip. For example, I used:
```
public class Anything
{
    static void RunCardinalToOrdinal()
    {
        for (int number = 1; number <= 40; number++)
        {
            Write($"{CardinalToOrdinal(number)} ");
        }
        WriteLine();
    }

    /// <summary>
    /// Pass a 32-bit integer and it will be converted into its ordinal equivalent.
    /// </summary>
    /// <param name="number">Number is a cardinal value e.g. 1, 2, 3, and so on.</param>
    /// <returns>Number as an ordinal value e.g. 1st, 2nd, 3rd, and so on.</returns>
    static string CardinalToOrdinal(int number)
    {
        switch (number)
        {
            case 11: // special cases for 11th to 13th
            case 12:
            case 13:
                return $"{number}th";
            default:
                int lastDigit = number % 10;
                string suffix = lastDigit switch
                {
                    1 => "st",
                    2 => "nd",
                    3 => "rd",
                    _ => "th"
                };
                return $"{number}{suffix}";
        }
    }
}
```
I will keep this issue open and try again in a later update.
