### ISSUE TITLE
Suggestion to optimize related tables data retrieval

### ISSUE THREAD

**Issue by cristiano1965** [markjprice/cs10dotnet6#56]
Dear Mark,
In page 648/649 I added some code to retrieve model.Category values with a second LINQ query, to show Product.Category.CategoryName in the view
........
Product? model = db.Products.SingleOrDefault(p => p.ProductId == id);

            if (model is null)
                {
                    return NotFound($"Product with ID={id} was not found");
                }
            model.Category = db.Categories.SingleOrDefault(c=>c.CategoryId == model.CategoryId);

            return View(model); // pass model to view and return result
......
My  question for you: is there a better way to do it without the second LINQ query, perhaps using a GETTER method in Product Class ?

Thanks for your suggestion.

Cristiano

**Comment by markjprice** [comment]
Hi Cristiano,

Yes, a better way is to call the `Include` method to fetch any related data you want in the original query, as shown in the following code:
```
Product? model = await db.Products.Include(p => p.Category)
        .SingleOrDefaultAsync(p => p.ProductId == id);
```
Then in the view you could do something like this to output both the category's Id and Name:
```
<dd>@Model.CategoryId - @Model.Category.CategoryName</dd>
```
I hope this helps.

**Comment by markjprice** [comment]
Page 434 shows how to use Include to fetch related data. 
Page 435 explains filtered includes. 
Page 446 shows how to stop using Include (which eagerly loads related data) so that you can explore other types of loading.
Page 448 shows the code to enable eager loading by using Include.
Page 460 has a code example of using Include to get courses related to a student.
Page 659 shows using Include to get the related category and supplier for a product to show related data in the view.

**Comment by cristiano1965** [comment]
Dear Mark,

Manyn thanks for your precious help.

Regards.
