### ISSUE TITLE
Exercise 17.3: how to call customer's web service from NavMenu

### ISSUE THREAD

**Issue by cristiano1965** [markjprice/cs10dotnet6#61]
Dear Mark,

I was trying to practice the exercise 17.3 on page 768, but even if I wrote the method, in CustomersController to return the list of country names (as an array of strings), I get frustrated because I don’t understand how to call it from from the NavMenu component in NavMenu.razor !!!

When you write "creating a menu item for each country" how can it be done without a NavLink ?

I enclose the sources with my modification but no luck !!!

[CustomersController.cs.txt](https://github.com/markjprice/cs10dotnet6/files/8716494/CustomersController.cs.txt)
[NavMenu.razor.txt](https://github.com/markjprice/cs10dotnet6/files/8716467/NavMenu.razor.txt)

Can you please help me ?

Thanks.

Cristiano

**Comment by markjprice** [comment]
Hi Cristiano,

I think I should rewrite that exercise because it is too difficult to achieve in the Blazor WebAssembly project using dynamic component construction in the web browser. (I might try to create a solution though when I have time.)

I had intended it to be for the Blazor Server project which is easier to implement since it all runs on the server-side but I did not make that clear. You are very close to the answer for that.

In the `Northwind.BlazorServer` project, in `INorthwindService.cs`, I added the following:
```cs
List<string?> GetCountries();
```
In `NorthwindService.cs`, I added the following:
```cs
public List<string?> GetCountries()
{
  return db.Customers.Select(c => c.Country).Distinct().OrderBy(country => country).ToList();
}
```
In `NavMenu.razor`, I added the following:
```cs
@foreach(string? country in northwind.GetCountries())
{
    string countryLink = "customers/" + country;

    <div class="nav-item px-3">
        <NavLink class="nav-link" href="@countryLink">
        <span class="oi oi-people" aria-hidden="true"></span>
        Customers in @country
        </NavLink>
    </div>
}
```
> Warning! You cannot use `<NavLink class="nav-link" href="customers/@c">` because Blazor does not allow combined text and @ expression in components. That is why my code above creates a local variable to do the combining to make the countryLink.

**Comment by cristiano1965** [comment]
Dear Mark,

Now it sounds and with your indications I got the Northwind.Blazorserver working, showing menu as per attached image, with all new links working
![working_filled_menu](https://user-images.githubusercontent.com/66923229/169282915-5082c377-2a55-4542-9856-87d4e61e649a.png)

Many thanks for your precious help.

Cristiano

**Comment by cristiano1965** [comment]
... I also removed the "height: vh100" in .sidebar in MainLayout.razor.css to get the sidebar background occupy the whole links list....
![working_filled_menu](https://user-images.githubusercontent.com/66923229/169285201-7941edbe-487c-44a6-8ec6-797990399dd9.png)
