### ISSUE TITLE
Practical Apps - Customer records deletion issue

### ISSUE THREAD

**Issue by alshuriga** [markjprice/cs10dotnet6#83]
In a few projects of Practical Apps solution/workspace, the problem of deleting customer records exists. 
When trying to delete a record that has one or more orders by using the method from the book it throws an sqlite "foreign key constraint failed" exception. 
I fixed it by implementing eager loading by using Include method in a LINQ expression, like this: 
```
public async Task<bool?> DeleteAsync(string id)
    {
        id = id.ToUpper();
        Customer? c = db.Customers.Include(c => c.Orders).ThenInclude(o => o.OrderDetails).Where(c => c.CustomerId == id).First();
        if (c is null) return null!;
        db.Customers.Remove(c);
        int affected = await db.SaveChangesAsync();
        if (affected > 0)
        {
            if (customersCache is null) return null;
            return customersCache.TryRemove(id, out c);
        }
        else
        {
            return null;
        }
    }
```
Although it does the trick,  I wonder if there's more correct solution.

**Comment by markjprice** [comment]
With any relational database, the most correct solution when deleting a record with related records depends on how you want the system to behave. As you note, the current Northwind database as foreign key constraints defined to prevent deleting a customer record if it has related orders records (and they will have related order detail records). The business rule could be:

1. Catch the exception and tell the user they must manually delete any related records.
2. Catch the exception and offer to automatically delete any related records. Perhaps even show what those records would be.
3. Prefetch the related records and configure cascading deletes so that when the customer is deleted, it's related records are automatically deleted as well.
4. Disable the foreign key constraint so that customers can be deleted but the related records remain. Perhaps archive those orphan records.
5. Create a IsDeleted column for a customer record and set that instead of actually deleting.

It all depends on how you want the business logic to be implemented. Your solution is as "correct" as any other. :)

**Comment by markjprice** [comment]
These would be a good extended exercise for readers to implement. I will consider adding it to the next edition (with solution code of course).

**Comment by alshuriga** [comment]
Thanks for the detailed answer!
