### ISSUE TITLE
Chap 19  of Bonus Content - Insecure vs Unsecure

### ISSUE THREAD

**Issue by toddcarnes** [markjprice/cs10dotnet6#94]
I know it's nitpicky, but on pages 102 and 103, everywhere that you use the word "insecure", you should be using the word "unsecure".

**Comment by markjprice** [comment]
Thanks! I will fix that in the next edition.

**Comment by toddcarnes** [comment]
I'm looking forward to the next edition. I have bought the last three and plan to buy that one as well. :)

**Comment by markjprice** [comment]
Awesome! I'm glad you like them. BTW, there will be two books in November. You might only want to buy the second one: https://github.com/markjprice/apps-services-net7

I've been Googling and there is much debate about this so I'm so confused now! https://english.stackexchange.com/questions/19653/insecure-or-unsecure-when-dealing-with-security

Apparently the Oxford English Dictionary says that unsecure is obsolete. Unsecured is a word but not unsecure. Others say insecure should only applies to humans because they can feel it about themselves and therefore insecure should not be applied to inanimate objects. But then the free dictionary gives examples of applying insecure to footholds, air bases, borders, and fortresses: https://www.thefreedictionary.com/insecure

https://grammarhow.com/unsecure-vs-insecure/ says “Unsecure” should be used when saying that something is not secured or not guaranteed in any way. It usually never has been, either. “Insecure” should be used when saying that something lacks security, even if there was an intention to keep that thing secure.

What do you think?

**Comment by markjprice** [comment]
I'm going to do what you suggest and change to unsecure anyway.

**Comment by toddcarnes** [comment]
Yikes! it seems I've opened up quite a can of worms. You asked what I thought. I grew up being taught that insecure was only used to refer to people's feelings. Then again, I am 50+ years old and English, unlike some other languages like Latin, is a living language that is still evolving and changing every day. So, perhaps, I am behind the times. So, I think that since it is your book and not mine, you should do whatever feels most comfortable to you.

**Comment by markjprice** [comment]
No worries! It's always cool to hear from readers. I agree, the main argument that sways me is the human feelings element. I'll close this issue now that I've decided to standardize on "unsecure".
